[[redirects]]
  from = "/static/*"
  to = "https://www.google.com/static/:splat"
  status = 200

[[redirects]]
  from = "/adsid/google/ui/*"
  to = "https://adservice.google.com/adsid/google/ui/:splat"  
  status = 200

[[redirects]]
  from = "/js/*"
  to = "https://www.gstatic.com/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "https://www.gstatic.com/:splat"
  status = 200

[[redirects]]
  from = "/css2/*"
  to = "https://fonts.googleapis.com/:splat"
  status = 200

[[redirects]]
  from = "/generate_204/*"
  to = "https://i.ytimg.com/:splat"
  status = 200

[[redirects]]
  from = "/gen_204/*"
  to = "https://i.ytimg.com/:splat"
  status = 200

[[redirects]]
  from = "/watch/*"
  to = "https://www.youtube.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://www.google.com/:splat"
  status = 200